name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Java tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy 🚀
        run: |
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD --; then
            # Custom deployment logic
            # For example, you can use Git commands to push changes to the current branch
            git config --local user.email "bojana.koteska@gmail.com"
            git config --local user.name "bojanakoteska"
            git add .
            git commit -m "Deploy to current branch"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to deploy."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
